version: '3.3'

services:

  MySQL_Database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'Clinica-vet'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './database/db/data:/var/lib/mysql'
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

