version : '3.3'

services:

  MySQL_Database:
    image: mysql:latest
    volumes:
      - "./database/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'Clinica'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    cap_add:
          - SYS_NICE